### ISSUE TITLE
Unauthorized access exceptions in correctly configured environment

### ISSUE THREAD

**Issue by Rattenkrieg** [Azure/azure-event-hubs-dotnet#134] opened 2017-03-01 17:05 UTC
Roughly every hour I get bunch of errors
> Microsoft.Azure.EventHubs.EventHubsException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://{my-eventhubs}/partitions/{arbitrary-partition-number}'.

**There is no such behavior while using Windows.Azure.ServiceBus.EventHubs.**

Might be the cause for #132

**Comment by Rattenkrieg** [comment] 2017-03-01 17:35
Those errors are feeded in my processor host's OnError callback.

**Comment by serkantkaraca** [comment] 2017-03-01 21:40
Can you log the stack as well? In the meantime, I will check the code where we renew the auth token.

**Comment by serkantkaraca** [comment] 2017-03-01 23:39
There is one possibility which can cause unauthorized access failures actually. If there is clock skew between client and the Event Hubs service nodes, the auth token might expire before client realizes that. Current implementation accounts clock skew up to 5 minutes, i.e. client renews the token 5 minutes before it expires. Therefore, if the clock skew is bigger than 5 minutes the client can observe intermittent auth failures. Can you check whether this is the case for you clients?

**Comment by Rattenkrieg** [comment] 2017-03-02 08:21
Here is stacktrace:

> at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.EventHubs.PartitionReceiver.<ReceiveAsync>d__36.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<ReceivePumpAsync>d__19.MoveNext()

Actually my first guess was to check clock difference, but it appears to have almost no skew.
Might this be caused due to different time zones?

**Comment by serkantkaraca** [comment] 2017-03-02 17:25
Ok, I initially thought the management channel token was expiring, and spend some time there yesterday and couldn't see anything. When it comes to Receive, we have different mechanics to refresh the token near expiry time. I think we have a bug in our client which causes token to expire intermittently every 60 minutes. I probably can check in a fix today on dev branch. Many thanks for pointing this.

**Comment by serkantkaraca** [comment] 2017-03-02 17:52
Sent PR for the fix. https://github.com/Azure/azure-event-hubs-dotnet/pull/139

**Comment by serkantkaraca** [comment] 2017-03-10 21:22
We have decided to investigate the issue thoroughly. The proposed fix alone may not be addressing the bug. Couple questions:

1. How many partitions does your eventhub have?
2. Are you seeing multiple of UnAuth failures from the same partition?
3. How long does it take to recover? As you mentioned it happens roughly every 60 minutes. How long does it take from first error to last error?

**Comment by Rattenkrieg** [comment] 2017-03-10 21:55
1. We running on 128 partitions though currently only 12 contains data
2. That difficult to answer since there were lots of errors. We had switched back to legacy client recently and error-logs are retired due to retention policy. 
3. Errors arrives in spikes, like batch of errors for some fraction of set of partitions. Then everything calm for roughly an hour and then again spike of errors for some different fraction of partitions.

**Comment by serkantkaraca** [comment] 2017-03-10 22:51
And you don't see this issue on old .NET client although clients are running on the same machines?

**Comment by Rattenkrieg** [comment] 2017-03-10 23:41
Thats right, neither exceptions leaked nor side effects of fail-over observed.

**Comment by serkantkaraca** [comment] 2017-03-13 20:17
Thx for confirmation. We will update the thread once we have new findings to share.

**Comment by nrandell** [comment] 2017-05-03 15:11
I've just run into the same issue. In this case I'm have 2 partitions, but am only using one of them.  My app started at 14:54:10 and at 16:04:16 stopped with the following

```
2017-05-03 16:04:16 [Fatal] Error processing: "Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://sk-events.servicebus.windows.net/chliveloglines/consumergroups/livedashboards/partitions/0'."
Microsoft.Azure.EventHubs.EventHubsException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://sk-events.servicebus.windows.net/chliveloglines/consumergroups/livedashboards/partitions/0'.
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.PartitionReceiver.<ReceiveAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CooperHewitt.Shared.LineDownloader.<TryDownloadLinesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LiveDashboardProcessing.Program.<RunAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SceneSkope.Utilities.CommandLineApplications.ApplicationBase`1.Run(TArgs arguments)
2017-05-03 16:04:16 [Information] Finished
```

This looks pretty repeatable. Let me know if there is anything else I can do to help if this is the same problem.

**Comment by serkantkaraca** [comment] 2017-05-03 18:05
@nrandell 

When did the first failure happen? Is the failure you provided the first failure your app hit? I am trying to see if this happens after some exact number of minutes.

**Comment by nrandell** [comment] 2017-05-03 18:07
That was the first failure, approximately 70 minutes (14:54:10 to 16:04:16). I'm going to be getting this running continuously later today and can update with any additional information I find.

**Comment by serkantkaraca** [comment] 2017-05-04 01:44
Are you able to reproduce this every time after 70 minutes?

**Comment by nrandell** [comment] 2017-05-04 08:19
So this morning, start up at 07:05:17 and the error occurred at 08:10:19. 65 minutes.

**Comment by serkantkaraca** [comment] 2017-05-04 20:32
I see. Btw can you share your code after removing the secrets? I would like to run same client to reproduce this.

**Comment by nrandell** [comment] 2017-05-04 20:51
Here's the core code that I use - I've just copied and pasted a single code file. I may be able to slim down an example over the weekend if necessary. All the packages are the very latest versions from nuget. This code also uses Polly to handle the error and then close and reopen the client.

Let me know if this helps. 

```
using System;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.EventHubs;
using Newtonsoft.Json;
using Polly;
using SceneSkope.Utilities.Text;
using Serilog;

namespace CooperHewitt.Shared
{
    public class LineDownloader
    {
        private readonly string _connectionString;
        private readonly string _partitionName;
        private readonly string _consumerGroup;
        private EventHubClient _client;
        private PartitionReceiver _receiver;
        private readonly Policy _retryPolicy;
        private readonly long _epoch = DateTime.UtcNow.Ticks;
        private string _latestOffset;

        public LineDownloader(string host, string keyName, string keyValue, string eventHubName, string partitionName, string consumerGroup, string latestOffset)
        {
            var builder = new EventHubsConnectionStringBuilder(new Uri($"amqps://{host}"), eventHubName, keyName, keyValue);
            _connectionString = builder.ToString();
            _partitionName = partitionName;
            _consumerGroup = consumerGroup;
            _latestOffset = latestOffset;
            _retryPolicy = Policy
                .Handle<Exception>(ex =>
                {
                    switch (ex)
                    {
                        case EventHubsException _: return true;
                        case UnauthorizedAccessException _: return true;
                        case TimeoutException _: return true;
                        case SocketException _: return true;
                        default:
                            Log.Warning("Caught {exception} ({type}), but not handling", ex.Message, ex.GetType());
                            return false;
                    }
                })
                .WaitAndRetryForeverAsync(_ => TimeSpan.FromSeconds(10),
                (ex, ts) =>
                {
                    Log.Information("Caught {exception}, delaying for {ts}", ex.Message, ts);
                    return CloseClientIfRequiredAsync();
                });
        }

        private async Task CloseClientIfRequiredAsync()
        {
            try
            {
                if (_receiver != null)
                {
                    await _receiver.CloseAsync().ConfigureAwait(false);
                    _receiver = null;
                    await _client.CloseAsync().ConfigureAwait(false);
                    _client = null;
                    Log.Information("Receiver and client closed");
                }
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Error closing: {exception}", ex.Message);
                throw;
            }
        }

        private void CloseClientIfRequired()
        {
            if (_receiver != null)
            {
                _receiver.Close();
                _receiver = null;
                _client.Close();
                _client = null;
            }
        }

        private PartitionReceiver GetOrCreateReceiver()
        {
            var receiver = _receiver;
            if (receiver == null)
            {
                var client = EventHubClient.CreateFromConnectionString(_connectionString);
                client.RetryPolicy = RetryPolicy.NoRetry;
                _client = client;

                receiver = client.CreateEpochReceiver(_consumerGroup, _partitionName, _latestOffset ?? PartitionReceiver.StartOfStream, _latestOffset == null, _epoch);
                receiver.RetryPolicy = RetryPolicy.NoRetry;
                _receiver = receiver;
            }
            return receiver;
        }

        public async Task<(UploadedLine[] lines, string latestOffset)> TryDownloadLinesAsync(TimeSpan duration, CancellationToken ct)
        {
            using (ct.Register(() => CloseClientIfRequired()))
            {
                var events = (await ReceiveAsync(duration, ct).ConfigureAwait(false)) as IList<EventData>;
                var count = events?.Count ?? 0;
                if (count > 0)
                {
                    var lines = new UploadedLine[count];
                    for (var i = 0; i < count; i++)
                    {
                        var segment = events[i].Body;
                        var json = Encoding.UTF8.GetString(segment.Array, segment.Offset, segment.Count);
                        var line = JsonConvert.DeserializeObject<UploadedLine>(json);
                        lines[i] = line;
                    }
                    var latestOffset = events[count - 1].SystemProperties.Offset;
                    _latestOffset = latestOffset;
                    return (lines, latestOffset);
                }
                else
                {
                    return (null, null);
                }
            }
        }

        private Task<IEnumerable<EventData>> ReceiveAsync(TimeSpan duration, CancellationToken ct) =>
            _retryPolicy.ExecuteAsync(_ => GetOrCreateReceiver().ReceiveAsync(100, duration), ct, false);
    }
}


```

**Comment by serkantkaraca** [comment] 2017-05-19 21:35
@nrandell , I am working on the sample. Can you confirm that you are reproducing the issue on .NetCoreApp, not .Net?

**Comment by nrandell** [comment] 2017-05-20 05:27
Yes - a .netcoreapp

**Comment by serkantkaraca** [comment] 2017-05-22 17:49
During your repro, do your senders keep sending? How about the receivers? Do receivers keep reading new messages? I am testing a scenario where receivers might go idle and service closes the connection due to idle timeout. I wonder if this is your case.

**Comment by nrandell** [comment] 2017-05-22 18:32
The senders are sending continually - however my scenario I cannot split the senders across multiple partitions, so I'm only using a single partition. 
On the receive side, I'm only receiving from the single partition and never start up a partition receiver on the other partitions as I know they are unused.
So possibly an edge case, but I'm using this to get a customers set of log files streaming continually into processing server and they way their log files are created makes it hard to partition into multiple partitions, and I have to read them in time order on the receiver side.

**Comment by serkantkaraca** [comment] 2017-05-22 18:56
Single partition receive is OK. That will keep the connection alive. So it doesn't seem like idle connection getting closed and causing token to expire scenario. Can you check one thing on you client machine? Can you print the UtcNow and check whether that is correct? Token expiry is calculated on UTC and let's rule out clock skew.

**Comment by nrandell** [comment] 2017-05-22 19:48
Just run on the machine: Mon May 22 19:46:30 UTC 2017
It's a Linux Ubuntu 16.04 on Azure - so the time should be correct!

**Comment by serkantkaraca** [comment] 2017-05-22 20:02
Were you able to reproduce same issue on Windows? I was making my attempts on Windows so far. Let me run a client on Ubuntu as well.

**Comment by nrandell** [comment] 2017-05-22 20:04
I think so - I'll look at creating a simple example tomorrow that reproduces this. Is there a way I can send you an access key to read the data?

**Comment by serkantkaraca** [comment] 2017-05-22 20:06
Please contact me at "serkar at microsot.com"

**Comment by nrandell** [comment] 2017-05-22 20:07
ok - expect something tomorrow

**Comment by serkantkaraca** [comment] 2017-05-22 21:38
I have started running a receiver client on Ubuntu 16.04. I will let it run for a day and see if it ever hits token expiry.

**Comment by nrandell** [comment] 2017-05-23 06:11
I've created a test repository @ https://github.com/nrandell/event-hubs-dotnet-issue-134.git
I'll email access keys etc.

**Comment by nrandell** [comment] 2017-05-23 08:41
Quick follow up - this has been running for a few hours now and I've seen the message:

`Caught Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://sk-events.servicebus.windows.net/chliveloglines/consumergroups/bugtest/partitions/0'.`

So it looks like my test repository reproduces on Linux.

**Comment by serkantkaraca** [comment] 2017-05-23 15:54
Thx @nrandell, I will take a look that. My client was running on Ubuntu w/o any errors for more than 14 hours now. Apparently something is different in your implementation.

**Comment by serkantkaraca** [comment] 2017-05-23 18:27
This issue is rooted to token renewal on entity level SAS key. I will submit a PR today.

**Comment by serkantkaraca** [comment] 2017-05-23 20:15
Fix merged into dev branch. This will be part of our next release.

**Closed by serkantkaraca** 2017-05-23 20:15 UTC
Labels: bug

**Comment by cwe1ss** [comment] 2017-06-12 11:45
I'm experiencing the same errors. Any rough timeline on when 1.0.2 will be released?

**Comment by serkantkaraca** [comment] 2017-06-12 22:31
Planning to release 1.02 in the next 2 weeks. In the meantime, you can compile the client from dev branch and use it as a workaround.

**Comment by cwe1ss** [comment] 2017-06-27 07:21
@serkantkaraca Could you please release this asap? This is a pretty nasty bug IMO because our services are crashing all the time.

**Comment by goncalo-oliveira** [comment] 2017-06-27 12:25
@cwe1ss I've managed to workaround this by catching the exception (StorageException with unauthorize access) in the processor delegate (ProcessErrorAsync). When I catch the exception, I unregister the listener and re-register. This seems to resolve the issue, however, mine isn't a production environment yet and I wouldn't want to do this in such an environment. It does work though.
I do agree this should be published as soon as possible.

**Comment by cwe1ss** [comment] 2017-07-11 07:47
@serkantkaraca ping! please release a new version with this fix.

**Comment by cwe1ss** [comment] 2017-07-24 08:27
@serkantkaraca @jtaubensee another ping! This bug is still critical IMO - could you please release the new version - it's been 2 months now!

**Comment by goncalo-oliveira** [comment] 2017-07-24 08:59
I agree. This is a critical issue and should be patched as soon as possible. Hoping to be able to use this in a production environment anytime soon.
