### ISSUE TITLE
Xamarin.Android cannot connect to event hub/AMQP when on cellular

### ISSUE THREAD

**Issue by alexsorokoletov** [Azure/azure-event-hubs-dotnet#223] opened 2017-12-08 01:50 UTC
## Actual Behavior
1. Xamarin.Android app connects to event hub and starts sending data when on Wi-Fi
2. Switch to cellular
3. Receive an error when sending data. Results in no data being sent to event hub.
Re-creating event hub client does not help, restarting app does not help.

## Expected Behavior
1. Application continues sending data using cellular connection

## Versions  
- OS platform and version: Xamarin.Android 8.0.2.1
- .NET Version: Mono 5
- NuGet package version or commit ID: 1.0.3/1.10

Error details:
```
Exception message: An address incompatible with the requested protocol was used
Type of exception: System.Net.Sockets.SocketException
```

**Comment by alexsorokoletov** [comment] 2017-12-08 02:38
Example of error analytics from AppCenter from our app:
```
EVENT - Errors.TrackEHubException - {"timestamp":"_2017-12-08T02:36:04.3692700Z","stack":" at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Thro","message":"An address incompatible with the requested protocol was used","type":"SocketException"}	 
```

**Comment by serkantkaraca** [comment] 2017-12-08 17:36
Have you changed default transport type on the client?

**Comment by alexsorokoletov** [comment] 2017-12-08 17:43
@serkantkaraca we did not, connection string has ";TransportType=Amqp".
Should we change that websockets?

**Comment by serkantkaraca** [comment] 2017-12-08 17:51
No you don't need to switch to web-sockets. I just wanted to know about client configuration.

Does Android app also works when started on cellular data?

**Comment by alexsorokoletov** [comment] 2017-12-08 17:53
No, Android (this) issue is persistent to cellular connection.

**Comment by serkantkaraca** [comment] 2017-12-08 17:55
Can you provide me a code snippet that I can use to reproduce the issue? Please remove any secrets before sharing the code.

**Comment by alexsorokoletov** [comment] 2017-12-08 18:03
Here is an edited version without any secrets of what we use to send data to event hub.

```
public async Task<int> PostEventsToEventHub(string connectionString, string publisherId, List<DataItem> data)
{
	var eventHubClient = EventHubClient.CreateFromConnectionString(connectionString);
	var sent = 0;
	try
	{
		foreach (var dataItem in data)
		{
			var payload = JsonConvert.SerializeObject(dataItem);
			try
			{
				var eventData = new EventData(Encoding.UTF8.GetBytes(payload));
				await eventHubClient.SendAsync(eventData, publisherId);
				sent++;
			}
			catch (EventHubsException e)
			{
				TrackEHubException(e, data);
				var isRevoked = e.Message.ToLower().Contains("revoke");
				var exception = new CustomException(e.Message, e);
				exception.IsUnathorized = isRevoked;
				if (isRevoked)
				{
					exception.StatusCode = HttpStatusCode.Unauthorized;
				}
				throw exception;
				break;
			}
			//based on sample from Azure https://github.com/Azure/azure-event-hubs/blob/78ddce8f8ba620f597df3f2ab3f37898777a6163/samples/DotNet/Microsoft.Azure.EventHubs/SampleSender/Program.cs#L58
			await Task.Delay(10);
		}
	}
	catch (CustomException e)
	{
		throw e;
	}
	catch (Exception e)
	{
		TrackEvenHubExceptionWithData(e, data);		
	}
	return sent;
}
```

**Comment by serkantkaraca** [comment] 2017-12-08 19:44
Instead of giving up on the for loop, can you continue? Existing client should recover w/o requiring to create another one.

Btw, you are using client 1.1.0, right? For repro, I would like to stick to the same release.

**Comment by alexsorokoletov** [comment] 2017-12-08 19:46
@serkantkaraca we had to downgrade to 1.0.3 due to some build server issues (.net standard 2.0 requires Sierra+ and stuff like that).

We are retrying yes, but it is not resolving even after 30 minutes.

**Comment by serkantkaraca** [comment] 2017-12-08 21:10
I will try to run similar code on an Android device with cellular data. I will update the thread with results.

**Comment by alexsorokoletov** [comment] 2017-12-12 15:53
@serkantkaraca Hi! Wondering if you had any success in reproducing the problem?

**Comment by serkantkaraca** [comment] 2017-12-12 16:26
Not yet. Sorry this will take another day or 2. We have a service release on Wednesday and I have moved my focus on that. I will start working on this issue once I am done.

**Comment by serkantkaraca** [comment] 2017-12-19 21:17
I have started working on the sample today. I will update the thread with the results.

**Comment by serkantkaraca** [comment] 2017-12-20 00:09
I have built a sender client on Xamarin and I couldn't reproduce the issue. Tried with both 1.0.3 and 1.1.0 clients w/o success. I would like to build the with Mono and see whether this is Mono specific or not.

**Comment by tanwarsatya** [comment] 2018-02-15 18:24
Any update on this, we are facing same issue. @serkantkaraca  do you have code of the client you used to successfully send the data to eventhub.

**Comment by serkantkaraca** [comment] 2018-02-15 18:27
The issue is already fixed in Mono. You can follow it on this tread: https://github.com/mono/mono/issues/6428

I am not sure about their release schedule but once they release the fix you can start targeting that runtime.

**Comment by alexsorokoletov** [comment] 2018-02-15 19:35
I would suggest to use amqp websockets transport type. It is much more stable in our tests

**Comment by tanwarsatya** [comment] 2018-02-19 05:09
Yes we are also using websocket as @alexsorokoletov mentioned. Application works but only initially when data (wifi/cellular) connection  is available, once connection is lost and later available the data is not sent to eventhub. We are using the default retry policy, it should send data once the connection is available again. Please let us know about any update on this issue.

**Comment by tanwarsatya** [comment] 2018-02-26 01:32
The application is not working when on IPV6 cellular connection, changing the connection to IPV4 works.

**Comment by serkantkaraca** [comment] 2018-05-24 00:35
The issue is fixed on Mono

**Closed by serkantkaraca** 2018-05-24 00:35 UTC
