### ISSUE TITLE
Provide API to restart IEventProcessor manually

### ISSUE THREAD

**Issue by Rattenkrieg** [Azure/azure-event-hubs-dotnet#172] opened 2017-06-13 10:23 UTC
Currently there is only way to "notice" errors by `IEventProcessor.ProcessErrorAsync`. Users can't react and implement any recovery strategy. Only option is to log such exception and `PartitionPump` [will continue operate normally](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs#L172)
In many cases `IEventProcessor` used to accumulate lots of state between callbacks of `ProcessEventsAsync` (manually checkpointing at domain state transitions - may span across several batches of `ProcessEventsAsync`) and best strategy of response to errors (transient ones) is to "_Let it crash_" i.e. to discard all accumulated state and start processing from last checkpoint. So I'm asking to provide such API (may be in `PartitionContext` or `IEventProcessor`) that will led to restart of `IEventProcessor` - specifically `CloseAsync` -> new instantiation -> `OpenAsync` sequence. 
One obivous weay is to set `PartitionPump` to `Closed` or `Errored` state and let `PartitionManager` to handle everything else.
To be more concrete - my scenario is close to functionality that Azure StreamAnalytics provides: accumulate (very long) sequence of events and perfrom statistical operations. Another scenario is persisting enriched log to Azure Blobs Storage - in optimization purposes events are accumulated to blocks and then appended to some blob with metadata attached. In every such scenario in case of error (network, code bugs etc) it's more desired to restart `IEventProcessor` instance and continue operate from last checkpoint rather than apply retries or left state corrupted.

**Comment by serkantkaraca** [comment] 2017-06-16 20:07
If a host becomes unhealthy it should not block processing of messages. When you have multiple nodes or hosts, one of them should take over the processing and continue. I don't really see how you can recover network errors by restarting the host. A host should always recover on its own when root cause recovers.

On the other hand, If a partition gets stuck on a host with no message process then that is an obvious bug we need to fix.

**Comment by Rattenkrieg** [comment] 2017-06-21 13:12
Here I'm talking about third-party network errors completely not related to host itself.
Take a look at following scenario:

```csharp

    private Stream _buffer;

    public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
    {
        foreach (var eventData in messages)
        {
            var data = Deserialize<MyCustomEvent>(eventData);
            var interestingPart = Serialize(data.Field0, data.Field1);
            _buffer.Write(interestingPart);
        }
        if (_buffer.Length > 10MiB) // time to persist
        {
            await SomeThirdPartyService.PersistAsync(_buffer); // <- potential source of errors
            // clean-up buffer etc
            await context.CheckpointAsync();
        }
    }
```

Buffer accumulation may span several `ProcessEventsAsync` calls during which we're not touching `context.CheckpointAsync()` at all. We're checkpointing only when we got enough data and only after persisting it. If `SomeThirdPartyService.PersistAsync` fail host will swallow exception and will continue processing next messages from eventhub so contents of `_buffer` will be lost. If we were able to "reset" host and told it to begin prossesing messages since last checkpoint `_buffer` will be accumulated from scratch and no data will be missed.
Here I'm talking about pursuing **exactly-once semantics**. May be I'm trying to design it wrong way then I hope you can suggest me other (idiomatic) way to achive this.

**Comment by JamesBirdsall** [comment] 2017-06-21 17:39
Right now EPH is built to just keep going forward in the face of errors from user-supplied code, but you provide a good scenario for allowing the behavior to be user-selectable between "keep going" and "revert to last checkpoint". Perhaps we could do the revert if OnEvents throws a particular type of exception, otherwise just keep going.

Adding that behavior would open up the possibility of a partition getting stuck in an endless loop of reverting, so it might be necessary to count the number of reverts in a row and close the partition if the count goes too high.

**Comment by serkantkaraca** [comment] 2017-06-21 22:00
Thanks for the details, I can understand your better better now.

Here is what I can suggest. 

Option 1: If the client detects an error that it cannot recover then it can actually failfast. Since failure is detected before checkpoint is persisted, once fail-fast is complete either new process on the same node or some other host will take over the partition. This way the new partition owner could always restart from the last check-point.

Oprtion2: You can signal a master thread that controls hosts. If client detects an unrecoverable error it can signal controller and then the controller can unregister and register again. The controller can even conduct a graceful shutdown after closing hosts. This approach might be cleaner and provide a better chance to recover.

**Comment by Rattenkrieg** [comment] 2017-06-23 17:17
@JamesBirdsall I think we could place killswitch in `PartitionContext` so it would be clear to users and always in hand (in IntelliSense terms). In case of custom exception it only can be discovered by documentation/source code grokking, although I'm not a fan of exception-driven control flow. Anyway it's not the most principal part. Number of reverts and other such statistics could be placed in context as well like `public uint NumberOfRevertsForCurrentCheckpoint { get; }`.
@serkantkaraca I tend to the second approach as well, but please notice that I'm talking about such routine at partition level not the entire host.
Well here that how I see entire algorithm:

1. User discover needs to bail out during `ProcessEventsAsync`
2. She gracefully asks host/partition context for assistance
3. `CloseAsync` fires (may be in tandem with `ProcessErrorAsync`)
4. ctor and `OpenAsync` fires (potentially on new host)

If you haven't any objections I can send a PR.

**Comment by serkantkaraca** [comment] 2017-08-14 19:30
I still cannot understand how reopening the same partition in the same process would help. If error is unrecoverable in current host, then it won't recover after reopening the partition. Whatever reason is causing the issue we should fix it. The proposed solution is based on some assumptions w/o and actual bug or scenario.

**Comment by Rattenkrieg** [comment] 2017-08-26 16:05
@serkantkaraca in case of contaminated host partition worker can be handovered to healthy one. Or imagine situation when you have several potentialy **transient**-failing i/o calls inside your `ProcessEventAsync` - you have to wrap each by some retrying/circuit-breaker routine. According to proposed api you just "Let it crash".
Although I'm not anymore have to work with Event-Hubs and do not care about it either so feel free to close this issue.

**Closed** 2017-08-28 15:33 UTC
