### ISSUE TITLE
Fina

### ISSUE THREAD

**Issue by makar-sasha** [Azure/azure-event-hubs-dotnet#279] opened 2018-05-23 08:15 UTC
Hello

## Actual Behavior
High memory usage. We have updated app to Core 2.0. It reads from the particular partition. But every several hrs the memory quickly grows up to the server physical limits (about 6GB of ram) even without any event hub traffic. Memory profiling says it is because of large finalization queue. 

![heap](https://user-images.githubusercontent.com/1519465/40409598-15c0cd40-5e74-11e8-9e2c-4ccd5938dfa3.jpg)

As you see Generation 2 is about 173 MB (but it grows with no limit) but only 2MB is used. Mainly it is occupied with TimerHolder and TaskExceptionHolder with Amqp related calls.

![heap2](https://user-images.githubusercontent.com/1519465/40410424-774bf0a6-5e76-11e8-938e-3f57fb56e719.jpg)

No exceptions in the logs. Could you advise how to fix it? This is how we read the data
  
```
        public EventHubEventProcessor(string con)
        {
            var builder = new EventHubsConnectionStringBuilder(con) { TransportType = TransportType.Amqp, EntityPath = Env.EventHub };
            eventHubClient = EventHubClient.CreateFromConnectionString(builder.ToString());
            sender = eventHubClient.CreatePartitionSender(EventNamesToPartitionsMapper.GetPartitionId(EventStreamNames.Notifier));
        }

        public async Task RunAsync(IMessageHandler handler, CancellationToken ct, IServiceLogger logger)
        {
            offset = await checkpoint.ReadOffsetAsync().ConfigureAwait(false);
            var receiver = eventHubClient.CreateReceiver(PartitionReceiver.DefaultConsumerGroupName, 
                EventNamesToPartitionsMapper.GetPartitionId(transactionLogName), 
                string.IsNullOrEmpty(offset) ? EventPosition.FromEnd() : EventPosition.FromOffset(offset));

            while (!ct.IsCancellationRequested) await ReadAndProcessMessage(receiver, handler, ct, logger).ConfigureAwait(false);
            await receiver.CloseAsync().ConfigureAwait(false);
            await sender.CloseAsync().ConfigureAwait(false);
        }

        private async Task ReadAndProcessMessage(PartitionReceiver receiver, IMessageHandler handler, CancellationToken ct, IServiceLogger logger)
        {
            try
            {
                var datas = await receiver.ReceiveAsync(1, TimeSpan.FromSeconds(CloudConstants.EventHubReceiverTimeOut)).ConfigureAwait(false);
                var data = datas?.FirstOrDefault();
                if (data == null) return;
                await DispatchEvent(data, handler, ct, logger).ConfigureAwait(false);
                offset = data.SystemProperties.Offset;
                await checkpoint.UpdateOffsetAsync(offset).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                logger?.Message("EventProcessor", $"for {transactionLogName} stream event hub processor with ERROR '{ex}' and checkpoint {offset}");
                ct.WaitHandle.WaitOne(1000);
            }
        }
```

## Versions  
- OS platform and version: Windows Server 2016
- .NET Version: .Net Standard 2.0
- NuGet package version or commit ID: v2.0.0

**Comment by serkantkaraca** [comment] 2018-05-23 17:28
Does the stack belong to sender or the receiver?

What is the receive timeout set at CloudConstants.EventHubReceiverTimeOut?

**Comment by makar-sasha** [comment] 2018-05-23 19:11
It is on the receiver side.
EventHubReceiverTimeOut = 2 sec

**Comment by serkantkaraca** [comment] 2018-05-23 19:13
OK, this is a known issue that I am still investigating. It seems to be triggered by small receive timeout. Can you stick to default timeout for now until we have a fix?

**Comment by makar-sasha** [comment] 2018-05-23 19:23
thanks! could you specify the appropriate value for the timeout? or should I just ignore it?

**Comment by serkantkaraca** [comment] 2018-05-23 19:26
You can use ReceiveAsync overload w/o timeout argument. That will do 60 seconds default timeout.

https://github.com/Azure/azure-event-hubs-dotnet/blob/74202b922f1992d444c982727b2abc23471fff77/src/Microsoft.Azure.EventHubs/PartitionReceiver.cs#L140

**Comment by makar-sasha** [comment] 2018-05-24 19:17
I have removed Timeout parameter but looks like that happens again. About 6pm memory usage on new .Net Core services have increased on all virtual machines. 
![heap3](https://user-images.githubusercontent.com/1519465/40506793-fff9c246-5f9f-11e8-97e0-1074a8cc69cd.jpg)

it could be related to the event hub requests spike at the same time (but not on the partition the problematic service is reading) 
![heap4](https://user-images.githubusercontent.com/1519465/40506819-037beb88-5fa0-11e8-8423-b4875b82225a.jpg)
The issue is pretty critical, I will try to get process dump.

**Comment by serkantkaraca** [comment] 2018-05-30 00:47
Yes please, dump might help. Can you also tell more about below:

* Number of partitions.
* Average number of messages per partition.
* How often are the receivers created?

**Comment by makar-sasha** [comment] 2018-05-31 06:15
Actually I didn't get the problem for several days (with updated timeout) so was not able to create a dump.
Because of this we have added one more .Net Core service. 

- there are 32 partitions but the reader is created for particular one.

- the traffic is low and often the problem was detected during the nights without any messages on this partition.

- only 1 receiver is created for partition and could work for several days until Service Fabric move it to some other node.

I understand it is difficult to detect the problem. I will restore original timeout on test env and try to collect a dump if it will help.

**Comment by serkantkaraca** [comment] 2018-05-31 16:28
Small timeout is probably contributing to this problem. While you are waiting for a repro, I will try to reproduce the issue with idle traffic.

**Comment by serkantkaraca** [comment] 2018-06-06 19:57
Thanks I will work on the dump. One question though, was the traffic idle when memory usage grew?

**Comment by makar-sasha** [comment] 2018-06-06 20:39
yes, looks like this partition was not in use (I see only 4 messages in the log for today). if you are using JetBrains dotMemory I can provide a dump for it also.

**Comment by serkantkaraca** [comment] 2018-06-07 20:55
The issue seems to be at AMQP library. I have pulled in a dev who works on that domain. I will provide an update soon. In the meantime I am working on a repro to test the fix.

**Comment by makar-sasha** [comment] 2018-06-08 18:47
maybe you know any alternative .net core 2 event hub reader that we can use temporary? this issue killing our service fabric nodes quite often.  Devops have added scheduler to check process memory size every minute but sometimes it is not enough.

**Comment by serkantkaraca** [comment] 2018-06-08 18:57
There is no other .Net Standard client that I know. We have identified 2 issues at AMQP library which can cause the leak, and working on the fix today.

**Comment by serkantkaraca** [comment] 2018-06-08 20:20
We have fixed the issue in AMQP library and verified the fix. The fix will be part of official build probably in 2 weeks. If you are in hurry you can build the client with AMQP fix and see if it holds. Let me know what you want to do.

**Comment by makar-sasha** [comment] 2018-06-08 20:49
great news! thanks, as some services are already on prod environment I prefer to build it and test asap.

**Comment by makar-sasha** [comment] 2018-06-12 18:21
Could you provide some instructions how to get the fix locally?

**Comment by serkantkaraca** [comment] 2018-06-12 18:35
We are in the process of publishing new AMQP nuget package. This will include the fix. You can basically build your project with new package and deploy. I will let you know once the nuget package is out.

**Comment by serkantkaraca** [comment] 2018-06-14 00:19
AMQP Nuget package is published. https://www.nuget.org/packages/Microsoft.Azure.Amqp/2.3.1

Let me know if fix helps or not.

**Comment by makar-sasha** [comment] 2018-06-15 11:39
Thanks! We have deployed the recent nuget and monitoring the work. Will notify you soon.

**Comment by makar-sasha** [comment] 2018-06-19 20:12
Actually it happens again. Also simultaneously on 60% of servers without event hub traffic. Please check the dump [https://1drv.ms/u/s!ArWkvwkTLUgmgoQ51ACQ0IK6yM4Efw](https://1drv.ms/u/s!ArWkvwkTLUgmgoQ51ACQ0IK6yM4Efw)

**Comment by makar-sasha** [comment] 2018-06-19 20:43
sorry, I have checked what version is deployed and it is from the old one. new services are ok.

**Comment by serkantkaraca** [comment] 2018-06-20 18:39
Happy to hear the fix helped. I am closing the issue now. Please let me know if you observe any issues with the new library.

**Closed by serkantkaraca** 2018-06-20 18:39 UTC
Labels: bug
