### ISSUE TITLE
Out of retries creating lease for partition

### ISSUE THREAD

**Issue by fvenezia** [Azure/azure-event-hubs-dotnet#299] opened 2018-07-23 16:44 UTC
Hi,
I get 'Out of retries creating lease for partition' whenever I try to use RegisterEventProcessorAsync method on EventProcessorHost class, even with .NET sample project at https://github.com/Azure/azure-event-hubs/tree/master/samples/DotNet/Microsoft.Azure.EventHubs
 
My connection strings are good since the client sample works fine.

Thanks for your help

**Comment by serkantkaraca** [comment] 2018-07-23 16:51
I have just moved the sample to SDK 2.1. Can you download and try again?

**Comment by fvenezia** [comment] 2018-07-24 11:15
I found the problem : the storage account was general purpose v1, I changed to blob storage and now it works fine.
I suggest to set a more accurate message to the exception when storage account API fails.
Thank you.

**Comment by serkantkaraca** [comment] 2018-07-24 15:53
Thx for pinpointing the issue. I will find out if we can improve the error message.

**Comment by babin93** [comment] 2018-09-11 19:29
Hi,
Could the last retry failure reason be included as an inner exception of the exception returned ? I had to debug for a while and checkout the EventProcessorHost to figure out that my problem that was not occuring all the time was caused by a too low version of NewtonSoft.Json that I was using. If the error message would have been included with the error, It would have been way easier for me to figure out what was my issue.

Thank you !

**Comment by serkantkaraca** [comment] 2018-09-11 20:07
Sure, I will look at that.

**Comment by serkantkaraca** [comment] 2018-09-11 23:45
PR https://github.com/Azure/azure-event-hubs-dotnet/pull/314

**Comment by serkantkaraca** [comment] 2018-10-05 15:29
SDK 2.2 is released with this fix.

**Closed by serkantkaraca** 2018-10-05 15:29 UTC
Labels: enhancement
