### ISSUE TITLE
PartitionReceiver.SetReceiveHandler not always pumping messages.

### ISSUE THREAD

**Issue by gambrose** [Azure/azure-event-hubs-dotnet#173] opened 2017-06-13 13:45 UTC
I'm seeing strange behaviour when using `PartitionReceiver.SetReceiveHandler` to subscribe and unsubscribe to events.

Looking at the code I see that `AmqpPartitionReceiver`.`ReceivePumpAsync` gets passed a local `CancellationToken` this is used to exit the pump but it always calls to `ReceiveHandlerClose` which cancels the `receivePumpCancellationSource` token. If the pump is stopped and started in quick succession then the closing pump could call though to `ReceiveHandlerClose` after then new pump has been created and will cancel the new newly started pump.

- NuGet package version or commit ID: 1.0.1

**Comment by serkantkaraca** [comment] 2017-06-16 20:15
Thanks for pointing this. I will check the code and update the thread.

**Comment by serkantkaraca** [comment] 2017-06-16 20:32
If you read the code again, this.receiveHandler is in the lock block and during register pump call a null value check determines whether to allow new pump registration or not. In other words, receiver won't allow new pump registration until current one is fully closed. Let me know if you are on the same page with me.

'        protected override void OnSetReceiveHandler(IPartitionReceiveHandler newReceiveHandler)
        {
            lock (this.receivePumpLock)
            {
                **if (newReceiveHandler != null && this.receiveHandler != null)**
                {
                    // Notify existing handler first (but don't wait).
                    this.receiveHandler.ProcessErrorAsync(new OperationCanceledException("New handler has registered for this receiver."));
                }
'

**Comment by gambrose** [comment] 2017-06-16 22:59
I was passing in a receive handler to start the pump. I was then passing in a null receive handler. This, I seem to remember, is the documented way to de-register the event. At this point the handler is null so a new handler is allowed but the old pump may or may not have stopped.

**Comment by serkantkaraca** [comment] 2017-06-17 00:23
The code guarantees that there is no active pump if this.receiveHandler == null. As you can see below, receiveHandler is set to null as the last thing in the Close code. At that point the pump is already stopped.

```
        void ReceiveHandlerClose()
        {
            lock (this.receivePumpLock)
            {
                if (this.receiveHandler != null)
                {
                    if (this.receivePumpTask != null)
                    {
                        this.receivePumpCancellationSource.Cancel();
                        this.receivePumpCancellationSource.Dispose();
                        this.receivePumpCancellationSource = null;
                        this.receivePumpTask = null;
                    }

                    this.receiveHandler = null; <<<<<<<<<<<<< 
                }
            }
        }
```

**Comment by gambrose** [comment] 2017-06-19 08:22
That code is problem as there is no guarantee that there can be only one pump at a time. There is a lock on the pump create but it still allows the calling code to null out the receive handler.

Here is a simple repo. If you run this against a partition with lots of events you get 2/3 events processed then it stops. But it should really continue.
I hope this helps illustrative my point.

```
class MyReceiveHandler : IPartitionReceiveHandler
{
    public Task ProcessEventsAsync(IEnumerable<EventData> events)
    {
        Console.WriteLine("Processing");
        return Task.Delay(TimeSpan.FromSeconds(1));
    }

    public Task ProcessErrorAsync(Exception error)
    {
        throw new NotImplementedException();
    }

    public int MaxBatchSize => 1;
}

var receiver = eventHubClient.CreateReceiver(consumerGroupName, partitionId, null);

IPartitionReceiveHandler receiveHandler = new MyReceiveHandler();

receiver.SetReceiveHandler(receiveHandler);
receiver.SetReceiveHandler(null);
receiver.SetReceiveHandler(receiveHandler);
```


To give you a little more context. I was implemented a source for a [reactive stream](https://github.com/reactive-streams/reactive-streams-dotnet) which requires me to slow down then stop the source if the downstream sinks can not keep up. In my case I have some buffers doing aggregation and when I set a breakpoint in the sink it would cause the buffers to fill quickly, as the consumer was blocked on my breakpoint, and the event hub source would be stopped but then when I continued the breakpoint the demand would be restored and the handler re-registered.
In the end I changed to write my only pump implementation that uses the `ReceiveAsync` method to pull events. This works better for me as I can also ensure that I only have one pump running by using `ContinueWith` on the task.

BTW, It would be nice if `PartitionReceiver.ReceiveAsync` had a overload that took an cancellation token.

**Comment by serkantkaraca** [comment] 2017-06-19 16:14
We are planning to have cancellation token support for all APIs, that will happen in the near future.

I will try to come up with a repro by modifying your code. I think if the issue is there, registering and then unregistering pump hundreds of times should give me a repro. I will update the thread in couple of hours.

**Comment by serkantkaraca** [comment] 2017-06-19 18:03
Thx for insisting on the issue. I finally got a repro and working on the fix. We will try to get a new client release this week and the fix will be part of that.

**Closed** 2017-08-23 18:35 UTC
Labels: bug
