### ISSUE TITLE
EventDataBatch Accepts EventData larger than maximum size EventHub will accept.

### ISSUE THREAD

**Issue by thelonelyvulpes** [Azure/azure-event-hubs-dotnet#413] opened 2020-03-10 16:54 UTC
## Actual Behavior
1. EventDataBatch.TryAdd accepts EventData larger than maximum size allowed by EventHub.

## Expected Behavior
1. Should return false and not add EventData to batch.

## Versions  
- OS platform and version: All
- .NET Version: All
- NuGet package version or commit ID:  https://github.com/Azure/azure-event-hubs-dotnet/commit/067e3a702e754fbe947d787de18dcb68023a7350

**Comment by serkantkaraca** [comment] 2020-03-10 19:03
It is by design. Client cannot send a message larger than 1 MB anyways.

**Comment by thelonelyvulpes** [comment] 2020-03-10 19:28
That's why it seems odd that you can add a EventData Successfully to a EventDataBatch that exceeds 1MB.

I've put some error handling in my client, but it's an easy pitfall.

**Comment by serkantkaraca** [comment] 2020-03-10 19:35
I understand it is not the perfect API experience and and also it is confusing. However, batch isn't aware of service side limits when it is newed up. Thus, it does its best.

**Comment by ramya-rao-a** [comment] 2021-02-26 20:23
@dev-gl 

Please note, a newer package is available [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs) as of February 2020. 
We encourage you to upgrade. See the [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.EventHubs_5.3.0/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md) for more details.

In the new package, the `EventDataBatch` is indeed aware of the batch size restrictions and will not allow adding any more `EventData` objects once the max size is reached. This however required us to make the method to create the batch async.

Please share any feedback or issues you have with the new package at https://github.com/azure/azure-sdk-for-net

@serkantkaraca 
I believe we can close this issue as we don't plan to change how the `EventDataBatch` works in `Microsoft.Azure.EventHubs` package?

cc @jsquire

**Comment by serkantkaraca** [comment] 2021-04-23 03:30
We are not planning to change the current batch behavior on the legacy SDK. I recommend migrating to https://www.nuget.org/packages/Azure.Messaging.EventHubs

**Closed as completed by serkantkaraca** 2021-04-23 03:30 UTC

**Comment by seble-nigussie** [comment] 2023-03-28 06:27
I'm using the latest eventhub nuget. I thought eventBatch.TryAdd is suppose to return false if data size exceeds the one specified in  CreateBatchOptions - MaximumSizeInBytes. Or am I wrong? It is now accepting data size greater than the one set in   MaximumSizeInBytes

**Comment by seble-nigussie** [comment] 2023-03-28 06:28
`var options = new CreateBatchOptions
                {
                    MaximumSizeInBytes = 25
                };

                using EventDataBatch eventBatch = await hubClient.CreateBatchAsync(options, token);
                var eventAdded = eventBatch.TryAdd(new EventData(data));`
