### ISSUE TITLE
AmqpPartitionReceiver.ReceivePumpAsync hangs when IPartitionReceiveHandler.ProcessErrorAsync throws

### ISSUE THREAD

**Issue by Rattenkrieg** [Azure/azure-event-hubs-dotnet#121] opened 2017-02-12 20:18 UTC
There is no protection in `AmqpPartitionReceiver.ReceivePumpAsync` against exceptions which may be throwed from `IPartitionReceiveHandle.ProcessErrorAsync`  
https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs#L303
When such occurs [receivePumpTask](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs#L20) completes in _Failed_ state and no progress being made by `AmqpPartitionReceiver` instance.
In `EventProcessorHost` scenario `PartitionReceiveHandler : IPartitionReceiveHandler` is just wrapper around `IEventProcessor` which [first defensively tries `Processor.ProcessEventsAsync` then simply calls `Processor.ProcessErrorAsync`](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs#L151)
If `Processor.ProcessEventsAsync` throws its exception propagates to [AmqpPartitionReceiver.ReceivePumpAsync](https://github.com/Azure/azure-event-hubs-dotnet/blob/8774bc4afbfbe44f1722ee648cbaca7ae07edede/src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs#L301) and goes one more time to `Processor.ProcessErrorAsync`.
If `Processor.ProcessErrorAsync` fails again on second call `AmqpPartitionReceiver` will end up hanged with its `receivePumpTask` being in _Failed_ state.
Here is [demonstration](https://github.com/Rattenkrieg/azure-event-hubs-dotnet/blob/dev/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L728) of such behavior.
I'm using `IPartitionReceiveHandler` since there is no way in current design to test directly on `IEventProcessor`, so in such test scenario only one exception from `IPartitionReceiveHandler.ProcessErrorAsync` is enough.

Proposed solution is to guard [this line](https://github.com/Azure/azure-event-hubs-dotnet/blob/8774bc4afbfbe44f1722ee648cbaca7ae07edede/src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs#L303) with try-catch OR to await/ContinueWith(..., TaskContinuationOptions.OnlyOnFaulted) on `receivePumpTask` and shut-down receiver instance (for example by setting `PartitionPumpStatus.Errored`)

**Comment by serkantkaraca** [comment] 2017-02-13 17:30
It is by design, PartitionReceiveHandler will shutdown on any error. It is host's responsibility to re-initiate receive handler. In EventProcessorHost case we do fail the pump on  any error from PartitionReceiveHandler. You can see that in PartitionReceiveHandler class in EventHubPartitionPump.cs in given code snipped below.

`            public async Task ProcessErrorAsync(Exception error)
            {
                if (error == null)
                {
                    error = new Exception("No error info supplied by EventHub client");
                }

                if (error is ReceiverDisconnectedException)
                {
                    ProcessorEventSource.Log.PartitionPumpWarning(
                        this.eventHubPartitionPump.Host.Id, this.eventHubPartitionPump.PartitionContext.PartitionId,
                        "EventHub client disconnected, probably another host took the partition");
                }
                else
                {
                    ProcessorEventSource.Log.PartitionPumpError(
                        this.eventHubPartitionPump.Host.Id, this.eventHubPartitionPump.PartitionContext.PartitionId, "EventHub client error:", error.ToString());
                }

                // We would like to deliver all errors in the pump to error handler.
                await this.eventHubPartitionPump.ProcessErrorAsync(error).ConfigureAwait(false);

                this.eventHubPartitionPump.PumpStatus = PartitionPumpStatus.Errored;
            }`

**Comment by Rattenkrieg** [comment] 2017-02-13 19:18
@serkantkaraca regarding your snippet from `PartitionReceiveHandler.ProcessErrorAsync(Exception error)`
`PumpStatus` will be set to `Errored` only if call to `ProcessErrorAsync` on previous line doesn't throw. PumpStatus should be set in finally block to guarantee state transition.

**Comment by serkantkaraca** [comment] 2017-02-13 20:07
Ok, I totally understand your point now. I am marking this one as a bug. I will provide a fix today.

**Comment by serkantkaraca** [comment] 2017-02-14 19:59
Fix merged into https://github.com/Azure/azure-event-hubs-dotnet/pull/117

**Closed** 2017-02-28 22:26 UTC
Labels: bug
