### ISSUE TITLE
Impossible to connect to the event hub a second time.

### ISSUE THREAD

**Issue by olegmanby** [Azure/azure-event-hubs-dotnet#383] opened 2019-03-25 09:00 UTC
Impossible to connect to the event hub a second time with the same host name and container lease name.  I noticed that it happens when the time of lease was expired.

Is it expected behavior?

## Versions  
- OS platform and version: Windows 10
- .NET Version: NET Standart 2.0
- NuGet package version or commit ID: v 3.0.0

**Comment by lolialoneathome** [comment] 2019-03-25 09:09
+1

**Comment by davidrevoledo** [comment] 2019-03-25 16:13
@OlegmanBY  do you a have a sample code to try to reproduce the error ? I will try to check :)

**Comment by serkantkaraca** [comment] 2019-03-25 20:09
Lease expiry and acquisition are the fundamentals of processor host library many tests depend and they are running alright. Can you please elaborate the issue a little more? I believe you are hitting some configuration problem.

**Comment by olegmanby** [comment] 2019-03-26 07:52
It is initializing of our event processor host. I run this code in console application. When we just close the application, we do not call StopAsync , UnregisterEventProcessorAsync and connect to EH again receiving events does not occur. If we wait for the application to close, everything is fine.

```csharp
public class EventHubListener<TConsumer, TEventModel> : IEventListener
        where TConsumer : IEventConsumer<TEventModel>
        where TEventModel : IEvent
    {
        private readonly EventHubConfiguration _configuration;
        private readonly EventProcessorFactory<TConsumer, TEventModel> _factory;
        private readonly EventProcessorHost _host;
        public EventHubListener(EventHubConfiguration configuration, EventProcessorFactory<TConsumer, TEventModel> factory)
        {
            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            _factory = factory ?? throw new ArgumentNullException(nameof(factory));

            _host = new EventProcessorHost(_configuration.EventProcessorHostName,
                _configuration.Path,
                _configuration.ConsumerGroup,
                _configuration.ConnectionString,
                _configuration.StorageConnectionString,
                _configuration.Name);
        }

        public async Task StartAsync()
        {
            await StopAsync();

            if (_configuration.IsEnabled)
            {
                _host.PartitionManagerOptions = new PartitionManagerOptions
                {
                    RenewInterval = TimeSpan.FromSeconds(5),
                    LeaseDuration = TimeSpan.FromSeconds(60),
                };
                await _host.RegisterEventProcessorFactoryAsync(_factory);
                Console.WriteLine("Receiving. Press ENTER to stop worker.");
            }
        }

        public async Task StopAsync()
        {
            if (_configuration.IsEnabled)
            {
                await _host.UnregisterEventProcessorAsync();
            }        
        }
    }```

**Comment by serkantkaraca** [comment] 2019-03-26 16:33
If you don't wait graceful shutdown of existing host, new host will wait until leases expire. Since your lease duration is 60 seconds, the wait time will be 60 seconds top. Let me know if you still don't see receives after that.

**Comment by olegmanby** [comment] 2019-03-27 07:11
>  If you don't wait graceful shutdown of existing host, new host will wait until leases expire

Could you please explain what the "new host" do you mean? We connect to EH with the same EH Host name and Container lease name. In case when we just closed our app, we can reconnect to EH within 60 sec and afterwards everything works correctly, but if we try to reconnect after 60 seconds when lease time was expired we experience technical issue that we do not receive events from EH without any exception.

**Comment by serkantkaraca** [comment] 2019-03-27 18:26
_host.RegisterEventProcessorFactoryAsync(_factory) creates a new instance of host . That is why I meant. 

This new host will wait until the very first lease is available as a result of lease expiry.

How many hosts are you running in total? Can you run with single host and see how stop/start behaves?

**Comment by olegmanby** [comment] 2019-03-28 07:28
We are running only one host instance for our application with the same host options (like a hostName, leaseContainerName and etc.) If you will change hostName everything works fine.

```csharp

static async Task MainAsync(string[] args)
        {
            Container = AutofacConfig.Configure();

            var listeners = Container.Resolve<IEnumerable<IEventListener>>();

            foreach (var listener in listeners)
            {
                await listener.StartAsync();
            }

            Console.WriteLine("PRESS ANY KEY TO STOP...");
            Console.ReadLine();

            foreach (var listener in listeners)
            {
                await listener.StopAsync();
            }
        }
```
Implementation of IEventListener you saw above. 

```csharp
public class EventProcessorFactory<TConsumer, TEventModel> : IEventProcessorFactory
        where TConsumer : IEventConsumer<TEventModel>
        where TEventModel : IEvent
    {
        private readonly IComponentContext _componentContext;

        public EventProcessorFactory(IComponentContext componentContext)
        {
            _componentContext = componentContext;
        }

        public IEventProcessor CreateEventProcessor(PartitionContext context)
        {
            return _componentContext.Resolve<EventProcessor<TConsumer, TEventModel>>();
        }
    }
```

```csharp
blic class EventProcessor<TConsumer, TEventModel> : IEventProcessor
        where TConsumer : IEventConsumer<TEventModel>
        where TEventModel : IEvent
    {
        private readonly TConsumer _consumer;
        public EventProcessor(TConsumer consumer)
        {
            _consumer = consumer;
        }

        public Task OpenAsync(PartitionContext context)
        {
            Console.WriteLine($"EventProcessor for {typeof(TEventModel)} initialized. Partition: '{context.PartitionId}'");
            return Task.CompletedTask;
        }

        public Task CloseAsync(PartitionContext context, CloseReason reason)
        {
            if (reason == CloseReason.Shutdown)
                return context.CheckpointAsync();

            Console.WriteLine($"EventProcessor for {typeof(TEventModel)} Shutting Down. Partition '{context.PartitionId}', Reason: '{reason}'.");
            if (reason == CloseReason.Shutdown)
                return context.CheckpointAsync();
            return Task.CompletedTask;
        }

        public Task ProcessErrorAsync(PartitionContext context, Exception error)
        {
            Console.WriteLine($"Error on Partition: {context.PartitionId}, Error: {error.Message} Type {typeof(TEventModel)}");
            return Task.CompletedTask;
        }

        public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
        {
            foreach (var message in messages)
            {
                var data = Encoding.UTF8.GetString(message.Body.Array, message.Body.Offset, message.Body.Count);
                using (MemoryStream memoryStream = new MemoryStream(message.Body.Array))
                {
                    TEventModel eventData;
                    using (var bsonReader = new BsonReader(memoryStream))
                    {
                        eventData = JsonSerializer.Create().Deserialize<TEventModel>(bsonReader);
                        await _consumer.ConsumeAsync(eventData);
                        await context.CheckpointAsync();
                    }
                    Console.WriteLine($"Message received. Partition: '{context.PartitionId}', Type {typeof(TEventModel).Name}");
                }
            }
        }
    }
```

**Comment by serkantkaraca** [comment] 2019-03-28 18:47
Thx, I will try the code and provide an update.

**Comment by serkantkaraca** [comment] 2019-03-28 19:27
Thanks for the code. I am able to reproduce the issue now. If this is blocking you please use a different host name each time. I will submit a fix today and hoping to release SDK 3.1 with this fix next week.

**Comment by serkantkaraca** [comment] 2019-03-28 20:07
PR for fix https://github.com/Azure/azure-event-hubs-dotnet/pull/387

**Comment by serkantkaraca** [comment] 2019-03-28 22:36
Fix merged into dev branch.

**Closed as completed by serkantkaraca** 2019-03-28 22:36 UTC
Labels: bug

**Comment by olegmanby** [comment] 2019-03-29 07:38
Thank you.
